apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: userspace-operator
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["example.com"]
    resources: ["userspaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
