FROM golang:1.23.4 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY ./cmd/minioth/ ./cmd/minioth/ 
RUN go env -w GONOSUMDB=github.com/kyri56xcaesar/minioth
RUN GOOS=linux go build -o ./cmd/minioth/minioth ./cmd/minioth/main.go 

FROM debian:bookworm-slim
WORKDIR /root/
RUN apt-get update && apt-get install -y libstdc++6 
COPY --from=builder /app/cmd/minioth/minioth .
COPY ./configs/minioth.env ./configs/ 

RUN chmod +x /root/minioth
CMD ["./minioth"]
