FROM gnuoctave/octave:latest

WORKDIR /app

RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install --break-system-packages boto3

COPY octave_app.py /app/
ENTRYPOINT [ "python3", "octave_app.py" ]