version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goprintffuncname
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - loggercheck
    - makezero
    - mirror
    - nakedret
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - godot
    - unused
    - wsl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
