apiVersion: v1
kind: ConfigMap
metadata:
  name: frontapp-config
  namespace: kuspace
data:
  frontapp.conf: |
    J_MAX_PARALLELISM=4
    J_MAX_TIMEOUT=10
    J_MAX_LOGIC_CHARS=1000000
    API_GIN_MODE=release
    PROFILE=container
    API_PORT=8079
    J_MAX_CPU=1
    J_MAX_MEM=33000
    J_MAX_STORAGE=4
    FRONT_ADDRESS=frontapp
    AUTH_ADDRESS=minioth
    J_WS_ADDRESS=46.103.183.191:30082
    ALLOWED_HEADERS=Origin,Content-Type,Authorization,Access-Control-Allow-Origin
    VERBOSE=true
    FRONT_PORT=8080
    AUTH_PORT=9090
    MINIO_DEFAULT_BUCKET=uspace-default
    IP=0.0.0.0
    API_ADDRESS=uspace
    WSS_ADDRESS_INTERNAL=wss:8082
    ALLOWED_ORIGINS=*
    ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT
