apiVersion: v1
kind: ConfigMap
metadata:
  name: frontapp-config
  namespace: kuspace
data:
  frontapp.conf: |
    PROFILE=container
    API_ADDRESS=uspace
    FRONT_PORT=8080
    J_MAX_LOGIC_CHARS=1000000
    MINIO_DEFAULT_BUCKET=uspace-default
    API_GIN_MODE=release
    FRONT_ADDRESS=frontapp
    AUTH_ADDRESS=minioth
    J_WS_ADDRESS=141.237.155.250:30082
    J_MAX_MEM=33000
    J_MAX_STORAGE=4
    J_MAX_PARALLELISM=4
    ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT
    J_MAX_CPU=1
    WSS_ADDRESS_INTERNAL=wss:8082
    ALLOWED_ORIGINS=*
    IP=0.0.0.0
    VERBOSE=true
    API_PORT=8079
    AUTH_PORT=9090
    ALLOWED_HEADERS=Origin,Content-Type,Authorization,Access-Control-Allow-Origin
    J_MAX_TIMEOUT=10
