apiVersion: v1
kind: ConfigMap
metadata:
  name: frontapp-config
  namespace: kuspace
data:
  frontapp.conf: |
    AUTH_ADDRESS=minioth.local
    ALLOWED_ORIGINS=*
    ALLOWED_HEADERS=Origin,Content-Type,Authorization,Access-Control-Allow-Origin
    J_MAX_CPU=1
    VERBOSE=true
    API_GIN_MODE=debug
    PROFILE=baremetal
    J_WS_ADDRESS=localhost:30082
    API_PORT=80
    AUTH_PORT=80
    J_MAX_MEM=33000
    J_MAX_STORAGE=4
    ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT
    IP=0.0.0.0
    API_ADDRESS=uspace.local
    J_MAX_LOGIC_CHARS=1000000
    MINIO_DEFAULT_BUCKET=uspace-default
    FRONT_PORT=8080
    J_MAX_PARALLELISM=4
    J_MAX_TIMEOUT=10
