apiVersion: v1
kind: ConfigMap
metadata:
  name: minioth-config
  namespace: kuspace
data:
  minioth.conf: |
    IP=0.0.0.0
    GIN_MODE=release
    API_PORT=9090
    ROOT_USERNAME=kuspaceadmin
    ALLOWED_ORIGINS=*
    ALLOWED_HEADERS=Origin,Content-Type,Authorization,Access-Control-Allow-Origin
    ALLOWED_METHODS=GET,POST,DELETE,PUT,OPTIONS,HEAD
    TLS_CERT_FILE=
    TLS_KEY_FILE=
    ISSUER=http://minioth:9090
    JWT_SIGNING_ALG=HS256
    HASH_COST=4
    PASSWORD_MIN_LENGTH=8
    PASSWORD_MAX_LENGTH=72
    PASSWORD_REQUIRE_UPPER=false
    PASSWORD_REQUIRE_LOWER=false
    PASSWORD_REQUIRE_DIGIT=false
    PASSWORD_REQUIRE_SPECIAL=false
    RATE_LIMIT_RPS=2
    RATE_LIMIT_BURST=10
