apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    STORAGE_SYSTEM=minio
    DB_JOBS=jobs.db
    DB_JOBS_PATH=data/db/uspace
    ALLOWED_ORIGINS=*
    ALLOWED_METHODS=*
    J_WS_ADDRESS=wss:8082
    DB_FSL_PATH=data/db/uspace
    DB_FSL_MAX_OPEN_CONNS=50
    LOCAL_VOLUMES_DEFAULT_CAPACITY=-1
    J_MAX_CPU=1
    FRONT_PORT=8080
    DB_FSL=fsl.db
    DB_FSL_MAX_IDLE_CONNS=10
    DB_FSL_MAX_IDLE_LIFETIME=10
    MINIO_ACCESS_KEY=minioadmin
    J_MAX_MEM=33000
    API_LOGS_PATH=data/logs/uspace/
    AUTH_PORT=9090
    J_MAX_LOGIC_CHARS=1000000
    MINIO_ENDPOINT=minio:9000
    OBJECT_SHARED=true
    ALLOWED_HEADERS=*
    J_DISPATCHER=scheduler
    J_MAX_TIMEOUT=10
    API_PORT=8079
    VERBOSE=true
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    DB_JOBS_MAX_OPEN_CONNS=50
    API_LOGS_MAX_SIZE=100
    J_WS_LOGS_PATH=data/logs/jobs/
    MINIO_NODEPORT_ENDPOINT=localhost:30101
    MINIO_DEFAULT_BUCKET=uspace-default
    J_MAX_STORAGE=4
    API_ADDRESS=uspace
    MINIOTH_ACCESS_KEY=kuspaceadmin
    J_QUEUE_SIZE=100
    J_MAX_PARALLELISM=4
    DB_JOBS_DRIVER=duckdb
    OBJECT_SIZE_THRESHOLD=400000000
    FSL_LOCALITY=false
    JWT_VALIDITY_HOURS=1
    PROFILE=container
    OBJECT_SHARE_EXPIRE=1440
    ONLY_PRESIGNED_UPLOAD=true
    FRONT_ADDRESS=frontapp
    MINIO_USE_SSL=false
    MINIO_OBJECT_LOCKING=false
    DB_JOBS_MAX_IDLE_CONNS=10
    NAMESPACE=kuspace
    J_MAX_WORKERS=10
    API_GIN_MODE=release
    FSL_SERVER=false
    J_EXECUTOR=kubernetes
    IP=0.0.0.0
    DB_FSL_DRIVER=duckdb
    DB_JOBS_MAX_IDLE_LIFETIME=10
    AUTH_ADDRESS=minioth
