apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    VERBOSE=true
    DB_FSL_MAX_IDLE_CONNS=10
    DB_FSL_MAX_IDLE_LIFETIME=10
    OBJECT_SHARED=true
    OBJECT_SIZE_THRESHOLD=400000000
    DB_JOBS=jobs.db
    DB_JOBS_MAX_IDLE_CONNS=10
    API_ADDRESS=uspace
    FSL_SERVER=false
    DB_FSL_PATH=data/db/uspace
    J_MAX_WORKERS=10
    J_MAX_LOGIC_CHARS=1000000
    ALLOWED_ORIGINS=*
    AUTH_PORT=9090
    IP=0.0.0.0
    STORAGE_SYSTEM=minio
    DB_FSL_MAX_OPEN_CONNS=50
    J_MAX_STORAGE=4
    API_LOGS_PATH=data/logs/uspace/
    FRONT_ADDRESS=frontapp
    LOCAL_VOLUMES_DEFAULT_CAPACITY=-1
    FSL_LOCALITY=false
    MINIO_NODEPORT_ENDPOINT=localhost:30101
    ALLOWED_METHODS=*
    J_WS_ADDRESS=wss:8082
    J_MAX_TIMEOUT=10
    ALLOWED_HEADERS=*
    DB_FSL=fsl.db
    MINIO_USE_SSL=false
    ONLY_PRESIGNED_UPLOAD=true
    J_MAX_CPU=1
    J_DISPATCHER=scheduler
    J_MAX_MEM=33000
    FRONT_PORT=8080
    J_EXECUTOR=kubernetes
    API_LOGS_MAX_SIZE=100
    MINIO_ENDPOINT=minio:9000
    DB_JOBS_PATH=data/db/uspace
    DB_JOBS_DRIVER=duckdb
    MINIO_OBJECT_LOCKING=false
    OBJECT_SHARE_EXPIRE=1440
    NAMESPACE=kuspace
    DB_FSL_DRIVER=duckdb
    J_MAX_PARALLELISM=4
    API_PORT=8079
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    JWT_VALIDITY_HOURS=1
    MINIOTH_ACCESS_KEY=kuspaceadmin
    J_WS_LOGS_PATH=data/logs/jobs/
    MINIO_ACCESS_KEY=minioadmin
    J_QUEUE_SIZE=100
    DB_JOBS_MAX_OPEN_CONNS=50
    MINIO_DEFAULT_BUCKET=uspace-default
    DB_JOBS_MAX_IDLE_LIFETIME=10
    API_GIN_MODE=release
    PROFILE=container
    AUTH_ADDRESS=minioth
