apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    MINIO_NODEPORT_ENDPOINT=localhost:30101
    OBJECT_SIZE_THRESHOLD=400000000
    DB_JOBS=jobs.db
    API_LOGS_PATH=data/logs/uspace/
    STORAGE_SYSTEM=minio
    J_WS_ADDRESS=wss:8082
    DB_FSL_DRIVER=duckdb
    OBJECT_SHARE_EXPIRE=1440
    J_MAX_TIMEOUT=10
    OBJECT_SHARED=true
    J_MAX_LOGIC_CHARS=1000000
    FRONT_ADDRESS=frontapp
    J_WS_LOGS_PATH=data/logs/jobs/
    DB_FSL_MAX_OPEN_CONNS=50
    FSL_LOCALITY=false
    MINIO_ACCESS_KEY=minioadmin
    AUTH_ADDRESS=minioth
    JWT_VALIDITY_HOURS=1
    J_QUEUE_SIZE=100
    J_MAX_CPU=4
    PROFILE=container
    DB_JOBS_MAX_IDLE_CONNS=10
    FRONT_PORT=8080
    AUTH_PORT=9090
    DB_FSL_MAX_IDLE_CONNS=10
    API_GIN_MODE=release
    DB_FSL_PATH=data/db/uspace
    J_DISPATCHER=scheduler
    API_ADDRESS=uspace
    J_EXECUTOR=kubernetes
    DB_JOBS_DRIVER=duckdb
    ALLOWED_METHODS=*
    VERBOSE=true
    J_MAX_WORKERS=10
    DB_JOBS_MAX_OPEN_CONNS=50
    DB_JOBS_MAX_IDLE_LIFETIME=10
    ALLOWED_ORIGINS=*
    LOCAL_VOLUMES_DEFAULT_CAPACITY=-1
    MINIO_DEFAULT_BUCKET=uspace-default
    J_MAX_PARALLELISM=4
    MINIO_OBJECT_LOCKING=false
    J_MAX_STORAGE=4
    ALLOWED_HEADERS=*
    NAMESPACE=kuspace
    DB_FSL_MAX_IDLE_LIFETIME=10
    DB_FSL=fsl.db
    DB_JOBS_PATH=data/db/uspace
    MINIOTH_ACCESS_KEY=kuspaceadmin
    IP=0.0.0.0
    FSL_SERVER=false
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    MINIO_ENDPOINT=minio:9000
    MINIO_USE_SSL=false
    API_LOGS_MAX_SIZE=100
    ONLY_PRESIGNED_UPLOAD=true
    J_MAX_MEM=33000
    API_PORT=8079
