apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    JWT_VALIDITY_HOURS=1
    DB_FSL_MAX_IDLE_CONNS=10
    FSL_LOCALITY=false
    MINIO_NODEPORT_ENDPOINT=localhost:30101
    ONLY_PRESIGNED_UPLOAD=true
    OBJECT_SIZE_THRESHOLD=400000000
    J_EXECUTOR=kubernetes
    J_TTL=300
    FRONT_ADDRESS=frontapp
    MINIO_DEFAULT_BUCKET=uspace-default
    OBJECT_SHARE_EXPIRE=1440
    DB_JOBS_DRIVER=sqlite3
    DB_JOBS_MAX_OPEN_CONNS=50
    DB_JOBS_MAX_IDLE_LIFETIME=10
    API_LOGS_PATH=data/logs/uspace/
    API_LOGS_MAX_SIZE=100
    MINIO_USE_SSL=false
    MINIOTH_ACCESS_KEY=kuspaceadmin
    NAMESPACE=kuspace
    DB_FSL=fsl.db
    DB_FSL_PATH=data/db/uspace
    J_MAX_TIMEOUT=10
    DB_FSL_DRIVER=sqlite3
    FRONT_PORT=8080
    J_MAX_MEM=33000
    J_WS_ADDRESS=wss:8082
    FSL_SERVER=false
    DB_FSL_MAX_OPEN_CONNS=50
    J_MAX_WORKERS=50
    J_MAX_CPU=1
    AUTH_PORT=9090
    VERBOSE=true
    STORAGE_SYSTEM=minio
    J_WS_LOGS_PATH=data/logs/jobs/
    DB_FSL_MAX_IDLE_LIFETIME=10
    MINIO_ACCESS_KEY=minioadmin
    J_DISPATCHER=scheduler
    J_MAX_PARALLELISM=4
    DB_JOBS_PATH=data/db/uspace
    API_PORT=8079
    ALLOWED_HEADERS=*
    ALLOWED_METHODS=*
    API_GIN_MODE=release
    J_MAX_STORAGE=4
    MINIO_ENDPOINT=minio:9000
    DB_JOBS_MAX_IDLE_CONNS=10
    IP=0.0.0.0
    OBJECT_SHARED=true
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    LOCAL_VOLUMES_DEFAULT_CAPACITY=-1
    MINIO_OBJECT_LOCKING=false
    API_ADDRESS=uspace
    AUTH_ADDRESS=minioth
    ALLOWED_ORIGINS=*
    PROFILE=container
    J_QUEUE_SIZE=100
    J_MAX_LOGIC_CHARS=1000000
    DB_JOBS=jobs.db
