apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: frontapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontapp
            port:
              number: 8080
  - host: uspace.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uspace
            port:
              number: 8079
  - host: minioth.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minioth
            port:
              number: 9090

  - host: minio.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9090