apiVersion: v1
kind: Service
metadata:
  name: frontapp-nodeport
  labels:
    app: frontapp
  namespace: kuspace
spec:
  type: NodePort
  selector:
    app: frontapp
  ports:
    - name: frontapp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
      