apiVersion: v1
kind: Service
metadata:
  name: minioth-nodeport
  labels:
    app: minioth
  namespace: kuspace
spec:
  type: NodePort
  selector:
    app: minioth
  ports:
    - name: minioth
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090
      
