apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  labels:
    app: minio
  namespace: kuspace
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30101  # to contact it outside of the cluster
    - name: console
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30100 # to contact it outside of the cluster

