apiVersion: v1 
kind: Service 
metadata: 
  name: wss-nodeport 
  labels: 
    app: wss 
  namespace: kuspace
spec:
  type: NodePort 
  selector: 
    app: wss 
  ports: 
    - name: wss 
      protocol: TCP 
      port: 8082 
      targetPort: 8082 
      nodePort: 30082 # to contact it outside of the cluster