FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get install -y python3 python3-pip
RUN python3 -m pip install -r requirements.txt 



COPY caengine_app.py /app/
ENTRYPOINT ["python3", "caengine_app.py"]