networks:
  app_network:
    driver: bridge

services:
  minioth:
    build:
      context: .. 
      dockerfile: build/Dockerfile.minioth
    container_name: minioth
    networks:
      - app_network
    volumes:
      - ../data:/root/data
    
  uspace:
    build:
      context: ..
      dockerfile: build/Dockerfile.uspace 
    container_name: uspace 
    networks:
      - app_network
    volumes:
      - ../data:/root/data 

  frontapp:
    build:
      context: ..
      dockerfile: build/Dockerfile.frontapp
    container_name: frontapp 
    networks:
      - app_network
    ports: 
      - "8080:8080"

