apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: userspaces.myapp.example.com
spec:
  group: myapp.example.com
  names:
    kind: Userspace
    plural: userspaces
    singular: userspace
    shortNames:
    - uspc
  scope: Namespaced 
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                  description: "Unique username for the user"
                storageSize:
                  type: string
                  pattern: "^[1-9][0-9]*(Gi|Mi|G|M)$"
                externalSource:
                  type: string
                  format: uri
