apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
  namespace: kuspace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kuspace
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: kuspace
subjects:
- kind: ServiceAccount
  name: job-runner
  namespace: kuspace

roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
