apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minioth
  labels:
    app: minioth
  namespace: kuspace
spec:
  selector:
    matchLabels:
      app: minioth
  serviceName: minioth
  replicas: 1
  template:
    metadata:
      labels:
        app: minioth
    spec:
      containers:
      - name: minioth
        image: kyri56xcaesar/kuspace:minioth-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: web
        volumeMounts: # volume mount linked to a pv for database and perstent storage
        - name: database
          mountPath: /root/data
        - name: config # volume mount used for configuration
          mountPath: /root/configs/minioth.conf
          subPath: minioth.conf
        env: # environment variables used only for secrets
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret       
              key: JWT_SECRET_KEY      
        - name: SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret   
              key: SERVICE_SECRET_KEY   
        - name: MINIOTH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minioth-secret       
              key: MINIOTH_SECRET_KEY
      volumes:
      - name: config
        configMap:
          name: minioth-config
      - name: database
        persistentVolumeClaim:
          claimName: minioth-pvc
