apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uspace
  labels:
    app: uspace
  namespace: kuspace

spec:
  selector:
    matchLabels:
      app: uspace
  serviceName: uspace
  replicas: 1
  template:
    metadata:
      labels:
        app: uspace
    spec:
      serviceAccountName: job-runner  
      containers:
      - name: uspace
        image: kyri56xcaesar/kuspace:uspace-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8079
          name: web
        volumeMounts:
        - name: database
          mountPath: /root/data
        - name: config 
          mountPath: /root/configs/uspace.conf
          subPath: uspace.conf
        env: # environment variables used only for secrets
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret       
              key: JWT_SECRET_KEY      
        - name: SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret   
              key: SERVICE_SECRET_KEY    
        
      volumes:
      - name: config 
        configMap:
          name: uspace-config
      - name: database 
        persistentVolumeClaim:
          claimName: uspace-pvc
      #nodeSelector:
        # kubernetes.io/hostname: docker-desktop
        #kubernetes.io/hostname: minikube
