apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    type: local
  namespace: kuspace
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kuspace-default
  hostPath:
    path: /var/lib/docker/volumes/minio-data/_data
    type: DirectoryOrCreate
