apiVersion: v1
kind: PersistentVolume
metadata:
  name: uspace-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kuspace-default
  volumeMode: Filesystem
  hostPath:
    #path: /host_mnt/c/Users/kyri/uspace-storage # windows path (wsl)
    path: /mnt/uspace
    type: DirectoryOrCreate
