apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
  namespace: default
  #namespace: kuspace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  #namespace: kuspace
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: default
  #namespace: kuspace
subjects:
- kind: ServiceAccount
  name: job-runner
  namespace: default
 #namespace: kuspace

roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
