apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uspace
  labels:
    app: uspace
spec:
  selector:
    matchLabels:
      app: uspace
  serviceName: uspace
  replicas: 1
  template:
    metadata:
      labels:
        app: uspace
    spec:
      serviceAccountName: job-runner  
      containers:
      - name: uspace
        image: kyri56xcaesar/kuspace/uspace:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8079
          name: web
        volumeMounts:
        - name: www
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
