apiVersion: v1
kind: Service
metadata:
  name: uspace
  labels:
    app: uspace
  namespace: default 
  #namespace: kuspace

spec:
  selector:
    app: uspace
  ports:
    - name: http
      port: 8079          
      targetPort: 8079    
