apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    MINIO_DEFAULT_BUCKET=uspace-default
    OBJECT_SHARE_EXPIRE=1440
    ONLY_PRESIGNED_UPLOAD=true
    ALLOWED_HEADERS=*
    MINIOTH_ACCESS_KEY=kuspaceadmin
    API_LOGS_MAX_SIZE=100
    ALLOWED_ORIGINS=*
    DB_FSL_MAX_IDLE_CONNS=10
    LOCAL_VOLUMES_DEFAULT_CAPACITY=20
    MINIO_USE_SSL=false
    OBJECT_SIZE_THRESHOLD=400000000
    J_QUEUE_SIZE=100 # just for the default sched
    DB_JOBS_DRIVER=duckdb
    DB_JOBS_MAX_OPEN_CONNS=50
    JWT_VALIDITY_HOURS=1
    DB_FSL_PATH=data/db/uspace
    MINIO_ACCESS_KEY=minioadmin
    MINIO_OBJECT_LOCKING=false
    DB_JOBS_PATH=data/db/uspace
    DB_JOBS_MAX_IDLE_LIFETIME=10
    API_PORT=8079
    API_ADDRESS=uspace
    API_LOGS_PATH=data/logs/uspace/
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    FSL_LOCALITY=false
    MINIO_ENDPOINT=minio:9000
    J_DISPATCHER=scheduler
    J_EXECUTOR=kubernetes
    J_WS_ADDRESS=localhost:8082
    J_WS_LOGS_PATH=data/logs/jobs/
    IP=0.0.0.0
    STORAGE_SYSTEM=minio
    DB_FSL_MAX_IDLE_LIFETIME=10
    J_MAX_WORKERS=10 # just fo rhte default sched
    API_GIN_MODE=debug
    AUTH_ADDRESS=minioth
    ALLOWED_METHODS=*
    FSL_SERVER=false
    DB_FSL=fsl.db
    DB_JOBS=jobs.db
    FRONT_PORT=8080
    FRONT_ADDRESS=frontapp
    AUTH_PORT=9090
    DB_FSL_DRIVER=duckdb
    DB_FSL_MAX_OPEN_CONNS=50
    OBJECT_SHARED=true
    DB_JOBS_MAX_IDLE_CONNS=10
