apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NAMESPACE}
  name: job-manager
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: job-runner
  namespace: ${NAMESPACE}

roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
