apiVersion: v1
kind: ConfigMap
metadata:
  name: uspace-config
  namespace: kuspace
data:
  uspace.conf: |
    FSL_SERVER=false
    DB_FSL_MAX_OPEN_CONNS=50
    MINIO_OBJECT_LOCKING=false
    J_MAX_PARALLELISM=4
    J_WS_LOGS_PATH=data/logs/jobs/
    DB_JOBS_MAX_IDLE_CONNS=10
    API_PORT=8079
    API_LOGS_PATH=data/logs/uspace/
    DB_JOBS_DRIVER=duckdb
    DB_JOBS_MAX_OPEN_CONNS=50
    DB_JOBS_MAX_IDLE_LIFETIME=10
    FRONT_PORT=8080
    AUTH_ADDRESS=minioth
    ALLOWED_HEADERS=*
    LOCAL_VOLUMES_DEFAULT_CAPACITY=-1
    DB_FSL_MAX_IDLE_CONNS=10
    MINIO_ACCESS_KEY=minioadmin
    MINIO_USE_SSL=false
    J_MAX_MEM=33000 # Mi
    DB_JOBS_PATH=data/db/uspace
    API_GIN_MODE=debug
    FRONT_ADDRESS=frontapp
    NAMESPACE=kuspace
    OBJECT_SHARE_EXPIRE=1440
    ONLY_PRESIGNED_UPLOAD=true
    J_MAX_WORKERS=10 # just fo rhte default sched
    J_MAX_LOGIC_CHARS=1000000
    J_WS_ADDRESS=localhost:8082
    AUTH_PORT=9090
    ALLOWED_METHODS=*
    LOCAL_VOLUMES_DEFAULT_PATH=data/volumes
    STORAGE_SYSTEM=minio
    DB_FSL_MAX_IDLE_LIFETIME=10
    OBJECT_SHARED=true
    J_EXECUTOR=kubernetes
    J_MAX_CPU=4
    DB_JOBS=jobs.db
    API_ADDRESS=uspace
    MINIO_DEFAULT_BUCKET=uspace-default
    J_MAX_STORAGE=4
    J_MAX_TIMEOUT=10
    IP=0.0.0.0
    API_LOGS_MAX_SIZE=100
    JWT_VALIDITY_HOURS=1
    OBJECT_SIZE_THRESHOLD=400000000
    MINIO_ENDPOINT=minio:9000
    PROFILE=container
    DB_FSL=fsl.db
    DB_FSL_DRIVER=duckdb
    DB_FSL_PATH=data/db/uspace
    FSL_LOCALITY=false
    MINIO_NODEPORT_ENDPOINT=localhost:30101
    J_DISPATCHER=scheduler
    J_QUEUE_SIZE=100 # just for the default sched
    ALLOWED_ORIGINS=*
    MINIOTH_ACCESS_KEY=kuspaceadmin
