apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
#  namespace: kuspace
spec:
  serviceName: minio 
  replicas: 1 
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        - name: MINIO_ALLOW_GET_HEAD
          value: "true"
        command: ["/bin/bash", "-c"]
        args: ["minio server /data --console-address :9090"]
        resources:
          limits:
            memory: "4Gi"
            cpu: "4000m"
          requests:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
      nodeSelector:
        #kubernetes.io/hostname: docker-desktop
        kubernetes.io/hostname: minikube

