apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: default
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9090
      targetPort: 9090
