apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  labels:
    app: minio
  namespace: default
  #namespace: kuspace
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30100


# for the statefulset
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090
  clusterIP: None 
