# Deploys a new Namespace for the MinIO Pod
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: minio-dev # Change this value if you want a different namespace name
#  labels:
#    name: minio-dev # Change this value to match metadata.name
#---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: default # Change this value to match the namespace metadata.name
spec:
  volumes:
    - name: minio-storage
      persistentVolumeClaim:
        claimName: minio-pvc
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    env:
    - name: MINIO_ROOT_USER
      value: minioadmin # Change this value to match the MinIO root user
    - name: MINIO_ROOT_PASSWORD
      value: minioadmin # Change this value to match the MinIO root password
    - name: MINIO_ALLOW_GET_HEAD
      value: "true"
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9090
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: /data
      name: minio-storage # Corresponds to the `spec.volumes` Persistent Volume
  nodeSelector:
  #  kubernetes.io/hostname: minikube
    kubernetes.io/hostname: docker-desktop
  # kubernetes.io/hostname: kubealpha.local # Specify a node label associated to the Worker Node on which you want to deploy the pod.
  # volumes:
  # - name: localvolume
    #hostPath: # MinIO generally recommends using locally-attached volumes
    #  path: /home/kyri/Documents/myThesis/playground/minio/test_data # Specify a path to a local drive or volume on the Kubernetes worker node
    #  type: DirectoryOrCreate # The path to the last directory must exist
    # persistentVolumeClaim:
    #   claimName: minio-pvc
