apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  labels:
    app: frontapp
  namespace: kuspace
spec:
  selector:
    matchLabels:
      app: frontapp
  replicas: 1
  template:
    metadata:
      labels:
        app: frontapp
    spec:
      containers:
      - name: frontapp
        image: kyri56xcaesar/kuspace:frontapp-latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts: # volume mount used for configuration
        - name: config
          mountPath: /root/configs/frontapp.conf
          subPath: frontapp.conf
        env: # environment variables used only for secrets
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret       
              key: JWT_SECRET_KEY      
        - name: SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret   
              key: SERVICE_SECRET_KEY   
      volumes:
      - name: config
        configMap:
          name: frontapp-config
      