apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: wss 
  labels: 
    app: wss 
  namespace: kuspace
spec:
  selector:
    matchLabels:
      app: wss
  replicas: 1
  template:
    metadata:
      labels:
        app: wss
    spec:
      containers:
      - name: wss
        image: kyri56xcaesar/kuspace:wss-latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        volumeMounts: # volume mount used for configuration
        - name: config
          mountPath: /root/configs/wss.conf
          subPath: wss.conf
        env: # environment variables used only for secrets
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret       
              key: JWT_SECRET_KEY    
        - name: SERVICE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret   
              key: SERVICE_SECRET_KEY  
      volumes:
      - name: config
        configMap:
          name: wss-config