apiVersion: v1
kind: Service
metadata:
  name: frontapp
  labels:
    app: frontapp
  namespace: default 
  #namespace: kuspace
spec:
  selector:
    app: frontapp
  ports:
    - name: http
      port: 8080          # Internal cluster port
      targetPort: 8080    # Port your Pod container listens on
