definitions:
  kyri56xcaesar_kuspace_internal_utils.Resource:
    properties:
      accessed_at:
        type: string
      created_at:
        type: string
      gid:
        description: as in group id
        type: integer
      links:
        type: integer
      name:
        type: string
      path:
        type: string
      perms:
        type: string
      reader: {}
      rid:
        type: integer
      size:
        type: integer
      type:
        type: string
      uid:
        description: as in user id (owner)
        type: integer
      updated_at:
        type: string
      vid:
        type: integer
      vname:
        type: string
    type: object
  kyri56xcaesar_kuspace_internal_utils.Volume:
    properties:
      capacity:
        type: number
      created_at:
        type: string
      dynamic:
        type: boolean
      name:
        type: string
      object_count:
        type: integer
      path:
        type: string
      usage:
        type: number
      vid:
        type: integer
    type: object
  pkg_fslite.Admin:
    description: Admin login/registration payload
    properties:
      id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/register:
    post:
      consumes:
      - application/json
      description: Registers a new admin user into the system.
      parameters:
      - description: Admin username (optional if provided in body)
        in: query
        name: username
        type: string
      - description: Admin password (optional if provided in body)
        in: query
        name: password
        type: string
      - description: Admin registration data in body (optional)
        in: body
        name: admin
        schema:
          $ref: '#/definitions/pkg_fslite.Admin'
      produces:
      - application/json
      responses:
        "201":
          description: Admin registered successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Missing or invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error during registration
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Admin registration
      tags:
      - auth
  /admin/resource/copy:
    post:
      description: Copies a resource from one location to another within the system.
      parameters:
      - description: Source resource in format <volume_name>/<object_name>
        in: query
        name: source
        required: true
        type: string
      - description: Destination resource in format <volume_name>/<object_name>
        in: query
        name: dest
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Copy successful
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid format or missing arguments
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Copy a resource
      tags:
      - resource
  /admin/resource/delete:
    delete:
      consumes:
      - application/json
      description: Deletes a resource by JSON body or query params (name & volume).
      parameters:
      - description: Resource to delete
        in: body
        name: resource
        schema:
          $ref: '#/definitions/kyri56xcaesar_kuspace_internal_utils.Resource'
      - description: Name of the resource
        in: query
        name: name
        type: string
      - description: Volume name of the resource
        in: query
        name: volume
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful deletion
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request or invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error or internal failure
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a resource
      tags:
      - resource
  /admin/resource/download:
    get:
      description: Downloads a resource from a specified volume by filename.
      parameters:
      - description: 'Format: <volume_name>/<object_name>'
        in: query
        name: resource
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: File stream for download
          schema:
            type: file
        "400":
          description: Invalid request format
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Resource not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Download a resource
      tags:
      - resource
  /admin/resource/get:
    get:
      description: Retrieves resources using name or resource IDs (rids).
      parameters:
      - description: Resource name to search
        in: query
        name: name
        type: string
      - description: Comma-separated list of resource IDs
        in: query
        name: rids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of resources
          schema:
            items:
              $ref: '#/definitions/kyri56xcaesar_kuspace_internal_utils.Resource'
            type: array
        "400":
          description: Query or processing error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: No matching resources found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get one or more resources
      tags:
      - resource
  /admin/resource/stat:
    get:
      description: Retrieves the metadata of a specific resource using its volume
        and name.
      parameters:
      - description: 'Format: <volume_name>/<object_name>'
        in: query
        name: resource
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Resource metadata
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid input or formatting
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error during stat
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get metadata of a resource
      tags:
      - resource
  /admin/resource/upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads multiple files to the specified volume. Requires authentication.
      parameters:
      - description: Volume name
        in: query
        name: volume
        required: true
        type: string
      - description: Files to upload
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Files uploaded successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request or parse failure
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Failed to insert resource
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload one or more files to a volume
      tags:
      - resource
  /admin/uservolumes:
    get:
      description: Fetch user-to-volume mappings. (Currently only GET is implemented.
        PATCH/DELETE placeholders.)
      parameters:
      - description: Comma-separated user IDs to filter
        in: query
        name: uids
        type: string
      - description: Comma-separated volume IDs to filter
        in: query
        name: vids
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User volume claims retrieved
          schema:
            additionalProperties: true
            type: object
        "403":
          description: Method not allowed
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Manage user volume claims
      tags:
      - volume
  /admin/volume/delete:
    delete:
      consumes:
      - application/json
      description: Deletes a volume either from JSON body or query param `name`.
      parameters:
      - description: Volume object
        in: body
        name: volume
        schema:
          $ref: '#/definitions/kyri56xcaesar_kuspace_internal_utils.Volume'
      - description: Volume name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: volume deleted
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: deletion error or invalid input
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a volume
      tags:
      - volume
  /admin/volume/get:
    get:
      description: Retrieves volume details using query parameters.
      parameters:
      - description: Volume name
        in: query
        name: name
        type: string
      - description: Volume ID
        in: query
        name: vid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: volume info
          schema:
            items:
              $ref: '#/definitions/kyri56xcaesar_kuspace_internal_utils.Volume'
            type: array
        "400":
          description: retrieval error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get volume information
      tags:
      - volume
  /admin/volume/new:
    post:
      consumes:
      - application/json
      description: Registers a new volume with specified metadata.
      parameters:
      - description: Volume object
        in: body
        name: volume
        required: true
        schema:
          $ref: '#/definitions/kyri56xcaesar_kuspace_internal_utils.Volume'
      produces:
      - application/json
      responses:
        "200":
          description: volume created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: binding or creation error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new volume
      tags:
      - volume
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates an admin user and returns a token for access.
      parameters:
      - description: Admin username (optional if provided in body)
        in: query
        name: username
        type: string
      - description: Admin password (optional if provided in body)
        in: query
        name: password
        type: string
      - description: Admin credentials in request body (optional)
        in: body
        name: admin
        schema:
          $ref: '#/definitions/pkg_fslite.Admin'
      produces:
      - application/json
      responses:
        "200":
          description: Token returned on successful authentication
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Missing or invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Authentication failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Admin login
      tags:
      - auth
swagger: "2.0"
