name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Tests
        run: go test ./...

      - name: Build Binaries
        run: go build -o app ./cmd/service-a

  docker-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t service-a:latest -f Dockerfile .

      # Optionally push to registry or load into Minikube
      - name: Load into Minikube
        run: |
          minikube image load service-a:latest

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/
