apiVersion: v1
kind: PersistentVolume
metadata:
  name: minioth-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kuspace-default
  hostPath:
    path: /mnt/minioth
    type: DirectoryOrCreate
  volumeMode: Filesystem
