apiVersion: v1
kind: PersistentVolume
metadata:
  name: minioth-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minioth
  hostPath:
    #path: /host_mnt/c/Users/kyri/minioth-storage  # is this on my host? # windows path(wsl)
    path: /mnt/minioth
    type: DirectoryOrCreate
  volumeMode: Filesystem
